/usr/bin/time -f '%e' python ising.py 1
/usr/bin/time -f '%e' python ising.py 2
/usr/bin/time -f '%e' python ising.py 3
/usr/bin/time -f '%e' python ising.py 4
/usr/bin/time -f '%e' python ising.py 5
/usr/bin/time -f '%e' python ising.py 6
/usr/bin/time -f '%e' python ising.py 7
/usr/bin/time -f '%e' python ising.py 8
/usr/bin/time -f '%e' python ising.py 9
/usr/bin/time -f '%e' python ising.py 10
/usr/bin/time -f '%e' python ising.py 11
/usr/bin/time -f '%e' python ising.py 12
/usr/bin/time -f '%e' python ising.py 13
/usr/bin/time -f '%e' python ising.py 14
/usr/bin/time -f '%e' python ising.py 15
/usr/bin/time -f '%e' python ising.py 16
/usr/bin/time -f '%e' python ising.py 17
/usr/bin/time -f '%e' python ising.py 18
/usr/bin/time -f '%e' python ising.py 19
/usr/bin/time -f '%e' python ising.py 20
/usr/bin/time -f '%e' python ising.py 21
/usr/bin/time -f '%e' python ising.py 22
/usr/bin/time -f '%e' python ising.py 23
/usr/bin/time -f '%e' python ising.py 24
/usr/bin/time -f '%e' python ising.py 25
/usr/bin/time -f '%e' python ising.py 26
/usr/bin/time -f '%e' python ising.py 27
/usr/bin/time -f '%e' python ising.py 28
/usr/bin/time -f '%e' python ising.py 29
/usr/bin/time -f '%e' python ising.py 30
/usr/bin/time -f '%e' python ising.py 31
/usr/bin/time -f '%e' python ising.py 32
/usr/bin/time -f '%e' python ising.py 33
/usr/bin/time -f '%e' python ising.py 34
/usr/bin/time -f '%e' python ising.py 35
/usr/bin/time -f '%e' python ising.py 36
/usr/bin/time -f '%e' python ising.py 37
/usr/bin/time -f '%e' python ising.py 38
/usr/bin/time -f '%e' python ising.py 39
/usr/bin/time -f '%e' python ising.py 40
/usr/bin/time -f '%e' python ising.py 41
/usr/bin/time -f '%e' python ising.py 42
/usr/bin/time -f '%e' python ising.py 43
/usr/bin/time -f '%e' python ising.py 44
/usr/bin/time -f '%e' python ising.py 45
/usr/bin/time -f '%e' python ising.py 46
/usr/bin/time -f '%e' python ising.py 47
/usr/bin/time -f '%e' python ising.py 48
/usr/bin/time -f '%e' python ising.py 49
/usr/bin/time -f '%e' python ising.py 50
/usr/bin/time -f '%e' python ising.py 51
/usr/bin/time -f '%e' python ising.py 52
/usr/bin/time -f '%e' python ising.py 53
/usr/bin/time -f '%e' python ising.py 54
/usr/bin/time -f '%e' python ising.py 55
/usr/bin/time -f '%e' python ising.py 56
/usr/bin/time -f '%e' python ising.py 57
/usr/bin/time -f '%e' python ising.py 58
/usr/bin/time -f '%e' python ising.py 59
/usr/bin/time -f '%e' python ising.py 60
/usr/bin/time -f '%e' python ising.py 61
/usr/bin/time -f '%e' python ising.py 62
/usr/bin/time -f '%e' python ising.py 63
/usr/bin/time -f '%e' python ising.py 64
/usr/bin/time -f '%e' python ising.py 65
/usr/bin/time -f '%e' python ising.py 66
/usr/bin/time -f '%e' python ising.py 67
/usr/bin/time -f '%e' python ising.py 68
/usr/bin/time -f '%e' python ising.py 69
/usr/bin/time -f '%e' python ising.py 70
/usr/bin/time -f '%e' python ising.py 71
/usr/bin/time -f '%e' python ising.py 72
/usr/bin/time -f '%e' python ising.py 73
/usr/bin/time -f '%e' python ising.py 74
/usr/bin/time -f '%e' python ising.py 75
/usr/bin/time -f '%e' python ising.py 76
/usr/bin/time -f '%e' python ising.py 77
/usr/bin/time -f '%e' python ising.py 78
/usr/bin/time -f '%e' python ising.py 79
/usr/bin/time -f '%e' python ising.py 80
/usr/bin/time -f '%e' python ising.py 81
/usr/bin/time -f '%e' python ising.py 82
/usr/bin/time -f '%e' python ising.py 83
/usr/bin/time -f '%e' python ising.py 84
/usr/bin/time -f '%e' python ising.py 85
/usr/bin/time -f '%e' python ising.py 86
/usr/bin/time -f '%e' python ising.py 87
/usr/bin/time -f '%e' python ising.py 88
/usr/bin/time -f '%e' python ising.py 89
/usr/bin/time -f '%e' python ising.py 90
/usr/bin/time -f '%e' python ising.py 91
/usr/bin/time -f '%e' python ising.py 92
/usr/bin/time -f '%e' python ising.py 93
/usr/bin/time -f '%e' python ising.py 94
/usr/bin/time -f '%e' python ising.py 95
/usr/bin/time -f '%e' python ising.py 96
/usr/bin/time -f '%e' python ising.py 97
/usr/bin/time -f '%e' python ising.py 98
/usr/bin/time -f '%e' python ising.py 99
/usr/bin/time -f '%e' python ising.py 100
